# Generated by Django 4.2.3 on 2023-08-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_education_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(choices=[('School', 'School'), ('College', 'College'), ('Bachelor', 'Bachelor'), ('Master', 'Master')], max_length=8),
        ),
    ]
